language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
cache:
  directories:
  - node_modules
env:
- BANKER_TEST_SUITE=mocha

deploy:
  provider: heroku
  api_key:
    secure: ZT2GYA5sKWXCNO2EGjBvoOTYn6BrxFRbKrG6/G9u8KdppV5Lu16rRqdEVIpbFlDwmA3RMvtX2gWQP7YkmucDVkbQtfjTL0Zhz7EMLHgGUE6JlPuOfevSonLnx7MobTO2mcseTUMUbvRIAR/b+jW4fJRwacNiQTs99JPyzmGIu5fLgVxk2i7p6fOP9yP4be/eyhB/2Fgvs9exVoYBu2qSC6sVfOCyJs6mPSErBuGG2KvFQ2gdu+oHPdODswL93Dg81F/KoWf4HxE81IirrxhJUFXeAhSvOjGQDxasXLg5l/s4Df+FAJaOC40hG00mBpt+6TmvK2cKKdG/5jQElv6I8eCJ1ouT+I1gDc2idNN1N8zNjIM3Xu2nMLRQK4m4uFU+1RVhbjanOVpMjDLXZf8pfOOtH8Jf2CIkkFKHbzgN/r+uSVi13eJObDUhWAcWx7unU/l0AvO6rpELvndxT080EvQ/nMR8NOvqasJ11d3nBRvRTXQ5tIZamfx1ZSKi6BM8vfxplILDl5JOJ9dXgDMEhsvilKbG94+LCGdpE9vLUb1mjL36sVSlmNtXzJFmLfb0UIkcWZ1a+PtrGKvXKiwgHhHcTAtS4g+TIdjDe846D8BUs56zyxONxedA7cLvaYyCsXLhmhxHXRelBJFGQqfe7KW5bbi4l2AqseQwiWTKOQo=
  app: mwui-api
  on:
    repo: modernwebui/api
notifications:
  email:
    recipients:
      - modernwebui@gmail.com
      - michael.l.north@gmail.com
